### PR TITLE
Add information

### PR DESCRIPTION
**Pull request by ligi**
btw: I also think it could make sense to distinguish between "EIP not relevant" and "work not started" - currently they are handled the same - but we would get an better overview by seeing them as separate things IMHO

### CODE REVIEW

**Comment by timbeiko** [comment]
My weak preference at this point is to not have any projects listed here who haven't proactively added their status as it may lead to unreliable information. Won't merge this now as we'll probably discuss with @tvanepps this week what is the best way to handle these :+1:

**Comment by ligi** [comment]
So I need to remove the TREZOR one to get this merged?

**Comment by timbeiko** [comment]
@ligi can you add the information here: https://github.com/ethereum/eth1.0-specs/blob/master/network-upgrades/ecosystem-readiness.md? 

Thanks!

**Comment by ligi** [comment]
replaced by #193

**Pull request closed without merging**
